name       : plex-media-player
version    : 2.12.1
release    : 8
source     :
    - git|https://github.com/plexinc/plex-media-player.git : v2.12.1.871-6c71195e
license    : GPL-2.0-only
component  : multimedia.video
networking : yes
summary    : Plex Media Player is the go-to app for Home Theater PCs (HTPCs) connected to big screen TVs.
description: |
    Plex Media Player is the go-to app for Home Theater PCs (HTPCs) connected to big screen TVs.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcec)
    - pkgconfig(mpv)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sdl2)
rundeps    :
    - qt5-quickcontrols
setup      : |
    %cmake_ninja -DQTROOT=/usr/share/qt5/
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/plex-media-player.desktop $installdir/usr/share/applications/plex-media-player.desktop
    rm -f $installdir/usr/share/applications/plexmediaplayer.desktop
    rm -rf $installdir/usr/resources
