name       : plex-media-player
version    : 2.7.0
release    : 3
source     :
    - https://github.com/plexinc/plex-media-player/archive/v2.7.0.806-608417d4.tar.gz : 37641346e4958fcf64271eb8af16c47d7a264ca5be51a84aa74843e6a6aec109
license    : GPL-2.0
component  : multimedia.video
networking : yes
summary    : Plex Media Player is the go-to app for Home Theater PCs (HTPCs) connected to big screen TVs.
description: |
    Plex Media Player is the go-to app for Home Theater PCs (HTPCs) connected to big screen TVs.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcec)
    - pkgconfig(mpv)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sdl2)
rundeps    :
    - qt5-quickcontrols
setup      : |
    %cmake -DQTROOT=/usr/share/qt5/ .
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/plex-media-player.desktop $installdir/usr/share/applications/plex-media-player.desktop
    install -Dm00644 resources/images/icon.png $installdir/usr/share/pixmaps/plex-media-player.png
    rm -rf $installdir/usr/resources
