name       : plex-media-player
version    : 2.9.0
release    : 4
source     :
    - https://github.com/plexinc/plex-media-player/archive/v2.9.0.824-706dec50.tar.gz : cdb21fe5fdb59efedf7446ef4488072ef87f421d502e46acbb3ae83c798fdf44
license    : GPL-2.0-only
component  : multimedia.video
networking : yes
summary    : Plex Media Player is the go-to app for Home Theater PCs (HTPCs) connected to big screen TVs.
description: |
    Plex Media Player is the go-to app for Home Theater PCs (HTPCs) connected to big screen TVs.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcec)
    - pkgconfig(mpv)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sdl2)
rundeps    :
    - qt5-quickcontrols
setup      : |
    %cmake -DQTROOT=/usr/share/qt5/ .
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/plex-media-player.desktop $installdir/usr/share/applications/plex-media-player.desktop
    install -Dm00644 resources/images/icon.png $installdir/usr/share/pixmaps/plex-media-player.png
    rm -rf $installdir/usr/resources
