name       : plex-media-player
version    : 2.11.0
release    : 6
source     :
    - https://github.com/plexinc/plex-media-player/archive/v2.11.0.867-f27f8d2a.tar.gz : 9b8b2083d885fec5c6a8318e99688dd6ecb9596e356e4098bb480ff3288ed8ed
license    : GPL-2.0-only
component  : multimedia.video
networking : yes
summary    : Plex Media Player is the go-to app for Home Theater PCs (HTPCs) connected to big screen TVs.
description: |
    Plex Media Player is the go-to app for Home Theater PCs (HTPCs) connected to big screen TVs.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcec)
    - pkgconfig(mpv)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sdl2)
rundeps    :
    - qt5-quickcontrols
setup      : |
    %cmake_ninja -DQTROOT=/usr/share/qt5/
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/plex-media-player.desktop $installdir/usr/share/applications/plex-media-player.desktop
    rm -f $installdir/usr/share/applications/plexmediaplayer.desktop
    rm -rf $installdir/usr/resources
